version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgres
    networks:
      - postgres-network


  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - '6380:6379'
    networks:
      - postgres-network


networks:
  postgres-network:

volumes:
  postgres: