version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgres
    networks:
      - postgres-network


  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9412:9411"
    environment:
      - STORAGE_TYPE=mem
    restart: always

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - '6380:6379'
    networks:
      - postgres-network


networks:
  postgres-network:

volumes:
  postgres: