spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:8080"
      discovery:
        locator:
          enabled: true
      routes:
        # Patient Service
        - id: patient-service
          uri: http://localhost:8030
          predicates:
            - Path=/api/v1/patients/**
          filters:
            - name: CircuitBreaker
              args:
                name: patientServiceCircuitBreaker
                fallbackUri: forward:/fallback/patientServiceFallBack
            - RewritePath=/api/v1/patients/(?<segment>.*), /api/v1/patients/${segment}


        # Dentist Service
        - id: dentist-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/dentists/**
          filters:
            - name: CircuitBreaker
              args:
                name: dentistServiceCircuitBreaker
                fallbackUri: forward:/fallback/dentistServiceFallBack
            - RewritePath=/api/v1/dentists/(?<segment>.*), /api/v1/dentists/${segment}


        # Appointment Service
        - id: appointment-service
          uri: http://localhost:8031
          predicates:
            - Path=/api/v1/appointment/**
          filters:
            - name: CircuitBreaker
              args:
                name: appointmentServiceCircuitBreaker
                fallbackUri: forward:/fallback/appointmentServiceFallBack
            - RewritePath=/api/v1/appointment/(?<segment>.*), /api/v1/appointment/${segment}


springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: patient-service
        url: /api/v1/patients/v3/api-docs
      - name: dentist-service
        url: /api/v1/dentists/v3/api-docs
      - name: appointment-service
        url: /api/v1/appointment/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  tracing:
    sampling:
      probability: 0.1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        failure-rate-threshold: 50
        sliding-window-type: COUNT_BASED
        sliding-window-size: 100
        minimum-number-of-calls: 10
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 5
        automatic-transition-from-open-to-half-open-enabled: true
    instances:
      patientServiceCircuitBreaker:
        base-config: default
      dentistServiceCircuitBreaker:
        base-config: default
      appointmentServiceCircuitBreaker:
        base-config: default

okta:
  oauth2:
    issuer: https://dev-14999453.okta.com/oauth2/default
    client-id: 0oan8ht9iqNnXmWyx5d7
    client-secret: pq7Q8n3dgzL2SAApzRDpqKhGJzVow30-KagJvtiFVGOCbcmCF4YaBW9S-_52C8sL
    scopes: openid, profile, email, offline_access

server:
  port: 8020