server:
  port: 8020

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: patient-ms
          uri: lb://patient-ms
          predicates:
            - Path=/api/v1/patient/**
          filters:
            - RewritePath=/api/v1/patient(?<segment>/.*), /${segment}

        - id: patient-ms-swagger
          uri: lb://patient-ms
          predicates:
            - Path=/api/v1/patient/v3/api-docs
          filters:
            - RewritePath=/api/v1/patient/v3/api-docs, /v3/api-docs

        - id: patient-ms-swagger-ui
          uri: lb://patient-ms
          predicates:
            - Path=/api/v1/patient/swagger-ui/**
          filters:
            - RewritePath=/api/v1/patient/swagger-ui/(?<segment>.*), /swagger-ui/${segment}


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/