spring:
  application:
    name: auth-service


  mail:
    host: smtp.gmail.com
    port: 587
    username: harunov21@gmail.com
    password: vyom jsre edvt tbxu

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect



springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

server:
  port: 8089
