spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5434/
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect