spring:
  profiles:
    include:
      - db

  liquibase:
    enabled: false

  data:
    redis:
      port: 6379
      host: localhost

  application:
    name: appointment-service

  devtools:
    remote:
      restart:
        enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



resilience4j:
  circuitbreaker:
    instances:
      patientService:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

server:
  port: 8031
