spring:
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql:localhost://5434/


  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
