spring:
  profiles:
    include:
      - db

  liquibase:
    enabled: false

  data:
    redis:
      port: 6739
      host: localhost

  application:
    name: dentist-ms

  devtools:
    remote:
      restart:
        enabled: true

eureka:
  client:
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8084